### PR TITLE
all exercises completed

### PR DESCRIPTION
**Pull request by alphanumeric0101**
being a bit lazy here with the branching and pull requests, but here are all the exercises, don't worry about going over them, I feel I understand this side of things. the skel.css flle is from Skeleton (http://getskeleton.com/) and was just for reference.

### CODE REVIEW

**Comment by ziad-saab** [comment]
@alphanumeric0101 the address book layout looks weird at some resolutions. If you use percentages instead of pixel values, your UI can fill the screen.

**Comment by ziad-saab** [comment]
@alphanumeric0101 for boxes, see if you can do it using positioning instead of modifying the HTML and using floats.

**Comment by ziad-saab** [comment]
@alphanumeric0101 few comments about the "content" exercise:

1. Using `inline-block` for layouts has some pitfalls associated to it: first, whitespace in your HTML will affect the spacing of the boxes you are trying to layout. Second, `inline-blocks` act like text with regard to vertical alignment, so the blocks will usually be `vertical-align: top`. That still won't fix the extra spacing.

2. The top sections should be 25% width on large screen, 50% on medium and 100% on small. Using the `vw` unit instead of `%` here can work against you: imagine if I asked you to take the same layout, but wrap it in a `div` with a `max-width: 1000px; margin: auto`. A lot of sites do that to achieve a layout that is not too wide on large screens. Such a thing would break your layout because your widths would be expressed in % of the total viewport width rather than the width of their parent.

3. If you decide to go back on this and give it another go with `float` or `flex`, also remember the `box-sizing` property: you want to be able to say that your sections are some percentage of the width, but include paddings (and borders) in the calculation. Using `border-box` all around can help.

**Comment by alphanumeric0101** [comment]
mm ok cool, I've made note of all those comments, will look at it when I have time, which will probably only be the weekend.

**Pull request closed without merging**
