### PR TITLE
Exercise 3

### PR DESCRIPTION
**Pull request by Ulaize**

### CODE REVIEW

**Comment by nyanofthemoon** [comment]
ulaize
@Ulaize Desktop version should be 3 columns, tablet version 2 columns and mobile version 1 column.

**Comment by Ulaize** [comment]
I think this is fixed with my last pull request @nyanofthemoon Let me know :smile_cat:

**Comment by ziad-saab** [comment]
@Ulaize thank you for trying again! Look at my example and see how I'm using **three** foundation classes to get the responsive layout. Can you try to fix and understand why?

**Comment by Ulaize** [comment]
@ziad-saab I will look into this tomorrow. Gotta go home now :smile:

**Pull request closed without merging**
